"""Task lifecycle helpers: timezone, carry-forward, snoozes, demote."""

from datetime import datetime, date, timedelta, timezone
from unittest.mock import patch

from models import Task, TaskStatus, TaskType, User
from routes.tasks import (
    _app_today, _day_start, _day_start_hour,
    carry_forward, resolve_snoozes, demote_misclassified_today,
)


def _user(db):
    return db.query(User).filter(User.username == "testuser").first()


# Every test in this module needs the primary user to exist. Auto-applied.
import pytest

@pytest.fixture(autouse=True)
def _seed_user(primary_user_token):
    yield


def _mk_task(db, user_id, **kwargs):
    kwargs.setdefault("title", "t")
    kwargs.setdefault("task_type", TaskType.task)
    t = Task(owner_id=user_id, **kwargs)
    db.add(t)
    db.commit()
    db.refresh(t)
    return t


# ---------------------------------------------------------------------------
# _app_today: day_start_hour rolls calendar over later than midnight
# ---------------------------------------------------------------------------

def test_app_today_returns_yesterday_when_before_day_start(db_session):
    user = _user(db_session)
    user.timezone = "America/Los_Angeles"
    user.day_start_hour = 6
    db_session.commit()

    # 3am Los Angeles → still yesterday by app rules
    fake_now = datetime(2026, 5, 18, 3, 0, tzinfo=__import__("zoneinfo").ZoneInfo("America/Los_Angeles"))
    with patch("routes.task_lifecycle.datetime") as mock_dt:
        mock_dt.now.return_value = fake_now
        mock_dt.side_effect = lambda *a, **kw: datetime(*a, **kw)
        result = _app_today(user)
    assert result == date(2026, 5, 17)


def test_app_today_returns_today_after_day_start(db_session):
    user = _user(db_session)
    user.timezone = "America/Los_Angeles"
    user.day_start_hour = 6
    db_session.commit()
    fake_now = datetime(2026, 5, 18, 9, 0, tzinfo=__import__("zoneinfo").ZoneInfo("America/Los_Angeles"))
    with patch("routes.task_lifecycle.datetime") as mock_dt:
        mock_dt.now.return_value = fake_now
        mock_dt.side_effect = lambda *a, **kw: datetime(*a, **kw)
        result = _app_today(user)
    assert result == date(2026, 5, 18)


def test_day_start_hour_defaults_to_4():
    class _U:
        day_start_hour = None
    assert _day_start_hour(_U()) == 4


# ---------------------------------------------------------------------------
# carry_forward: yesterday's incomplete Today items return to inbox
# ---------------------------------------------------------------------------

def test_carry_forward_moves_yesterdays_today_tasks_to_inbox(db_session):
    user = _user(db_session)
    user.day_start_hour = 0  # gate always open during test
    db_session.commit()

    yesterday = _day_start(user) - timedelta(days=1)
    stale = _mk_task(db_session, user.id, status=TaskStatus.today, scheduled_date=yesterday)
    fresh = _mk_task(db_session, user.id, status=TaskStatus.today, scheduled_date=_day_start(user))

    moved = carry_forward(user, db_session)
    assert moved == 1
    db_session.refresh(stale)
    db_session.refresh(fresh)
    assert stale.status == TaskStatus.inbox
    assert stale.scheduled_date is None
    assert fresh.status == TaskStatus.today


def test_carry_forward_soft_deletes_missed_routines(db_session):
    """Stale routine instances should be deleted, not carried forward.
    They will be re-generated by `generate_routine_instances` on the next day."""
    user = _user(db_session)
    user.day_start_hour = 0
    db_session.commit()

    yesterday = _day_start(user) - timedelta(days=1)
    stale_routine = _mk_task(
        db_session, user.id, status=TaskStatus.today, scheduled_date=yesterday,
        task_type=TaskType.routine, routine_id=999,
    )

    carry_forward(user, db_session)
    db_session.refresh(stale_routine)
    assert stale_routine.status == TaskStatus.deleted


# ---------------------------------------------------------------------------
# resolve_snoozes: snoozed → inbox when snooze_until passes
# ---------------------------------------------------------------------------

def test_resolve_snoozes_unsnoozes_expired_only(db_session):
    user = _user(db_session)
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    expired = _mk_task(db_session, user.id, status=TaskStatus.snoozed,
                       snooze_until=now - timedelta(hours=1))
    future = _mk_task(db_session, user.id, status=TaskStatus.snoozed,
                      snooze_until=now + timedelta(hours=1))

    moved = resolve_snoozes(user, db_session)
    assert moved == 1
    db_session.refresh(expired)
    db_session.refresh(future)
    assert expired.status == TaskStatus.inbox
    assert expired.snooze_until is None
    assert future.status == TaskStatus.snoozed


# ---------------------------------------------------------------------------
# demote_misclassified_today: today w/ future due_date → inbox
# ---------------------------------------------------------------------------

def test_demote_moves_future_dated_today_tasks_back_to_inbox(db_session):
    user = _user(db_session)
    today = _app_today(user)
    bad = _mk_task(db_session, user.id, status=TaskStatus.today,
                   due_date=today + timedelta(days=3))
    ok = _mk_task(db_session, user.id, status=TaskStatus.today, due_date=today)

    moved = demote_misclassified_today(user, db_session)
    assert moved == 1
    db_session.refresh(bad)
    db_session.refresh(ok)
    assert bad.status == TaskStatus.inbox
    assert ok.status == TaskStatus.today


def test_demote_ignores_routines(db_session):
    user = _user(db_session)
    today = _app_today(user)
    routine_task = _mk_task(
        db_session, user.id, status=TaskStatus.today,
        due_date=today + timedelta(days=3),
        task_type=TaskType.routine, routine_id=1,
    )
    demote_misclassified_today(user, db_session)
    db_session.refresh(routine_task)
    assert routine_task.status == TaskStatus.today


def test_daily_rollover_generates_only_once_per_day(db_session, monkeypatch):
    """The atomic guard must let exactly one call per app-day run the once-daily
    sweeps — this is what stops concurrent loads spawning duplicate routines."""
    from routes import task_lifecycle as tl
    user = _user(db_session)
    user.day_start_hour = 0
    db_session.commit()

    calls = {"n": 0}
    real = tl.generate_routine_instances
    def _spy(u, d):
        calls["n"] += 1
        return real(u, d)
    monkeypatch.setattr(tl, "generate_routine_instances", _spy)

    assert tl.run_daily_rollover(user, db_session) is True     # wins, runs sweeps
    assert tl.run_daily_rollover(user, db_session) is False    # already done today
    assert calls["n"] == 1
