"""Task lifecycle helpers: timezone, carry-forward, snoozes, demote, promote."""

from datetime import datetime, date, timedelta, timezone
from unittest.mock import patch

from models import Task, TaskStatus, TaskType, User
from routes.tasks import (
    _app_today, _day_start, _day_start_hour,
    carry_forward, resolve_snoozes, demote_misclassified_today, promote_due_tasks,
    archive_past_appointments,
)


def _user(db):
    return db.query(User).filter(User.username == "testuser").first()


# Every test in this module needs the primary user to exist. Auto-applied.
import pytest

@pytest.fixture(autouse=True)
def _seed_user(primary_user_token):
    yield


def _mk_task(db, user_id, **kwargs):
    kwargs.setdefault("title", "t")
    kwargs.setdefault("task_type", TaskType.task)
    t = Task(owner_id=user_id, **kwargs)
    db.add(t)
    db.commit()
    db.refresh(t)
    return t


# ---------------------------------------------------------------------------
# _app_today: day_start_hour rolls calendar over later than midnight
# ---------------------------------------------------------------------------

def test_app_today_returns_yesterday_when_before_day_start(db_session):
    user = _user(db_session)
    user.timezone = "America/Los_Angeles"
    user.day_start_hour = 6
    db_session.commit()

    # 3am Los Angeles → still yesterday by app rules
    fake_now = datetime(2026, 5, 18, 3, 0, tzinfo=__import__("zoneinfo").ZoneInfo("America/Los_Angeles"))
    with patch("routes.task_lifecycle.datetime") as mock_dt:
        mock_dt.now.return_value = fake_now
        mock_dt.side_effect = lambda *a, **kw: datetime(*a, **kw)
        result = _app_today(user)
    assert result == date(2026, 5, 17)


def test_app_today_returns_today_after_day_start(db_session):
    user = _user(db_session)
    user.timezone = "America/Los_Angeles"
    user.day_start_hour = 6
    db_session.commit()
    fake_now = datetime(2026, 5, 18, 9, 0, tzinfo=__import__("zoneinfo").ZoneInfo("America/Los_Angeles"))
    with patch("routes.task_lifecycle.datetime") as mock_dt:
        mock_dt.now.return_value = fake_now
        mock_dt.side_effect = lambda *a, **kw: datetime(*a, **kw)
        result = _app_today(user)
    assert result == date(2026, 5, 18)


def test_day_start_hour_defaults_to_6():
    class _U:
        day_start_hour = None
    assert _day_start_hour(_U()) == 6


# ---------------------------------------------------------------------------
# carry_forward: yesterday's incomplete Today items return to inbox
# ---------------------------------------------------------------------------

def test_carry_forward_moves_yesterdays_today_tasks_to_inbox(db_session):
    user = _user(db_session)
    user.day_start_hour = 0  # gate always open during test
    db_session.commit()

    yesterday = _day_start(user) - timedelta(days=1)
    stale = _mk_task(db_session, user.id, status=TaskStatus.today, scheduled_date=yesterday)
    fresh = _mk_task(db_session, user.id, status=TaskStatus.today, scheduled_date=_day_start(user))

    moved = carry_forward(user, db_session)
    assert moved == 1
    db_session.refresh(stale)
    db_session.refresh(fresh)
    assert stale.status == TaskStatus.inbox
    assert stale.scheduled_date is None
    assert fresh.status == TaskStatus.today


def test_carry_forward_soft_deletes_missed_routines(db_session):
    """Stale routine instances should be deleted, not carried forward.
    They will be re-generated by `generate_routine_instances` on the next day."""
    user = _user(db_session)
    user.day_start_hour = 0
    db_session.commit()

    yesterday = _day_start(user) - timedelta(days=1)
    stale_routine = _mk_task(
        db_session, user.id, status=TaskStatus.today, scheduled_date=yesterday,
        task_type=TaskType.routine, routine_id=999,
    )

    carry_forward(user, db_session)
    db_session.refresh(stale_routine)
    assert stale_routine.status == TaskStatus.deleted


# ---------------------------------------------------------------------------
# resolve_snoozes: snoozed → inbox when snooze_until passes
# ---------------------------------------------------------------------------

def test_resolve_snoozes_unsnoozes_expired_only(db_session):
    user = _user(db_session)
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    expired = _mk_task(db_session, user.id, status=TaskStatus.snoozed,
                       snooze_until=now - timedelta(hours=1))
    future = _mk_task(db_session, user.id, status=TaskStatus.snoozed,
                      snooze_until=now + timedelta(hours=1))

    moved = resolve_snoozes(user, db_session)
    assert moved == 1
    db_session.refresh(expired)
    db_session.refresh(future)
    assert expired.status == TaskStatus.inbox
    assert expired.snooze_until is None
    assert future.status == TaskStatus.snoozed


# ---------------------------------------------------------------------------
# demote_misclassified_today: today w/ future due_date → inbox
# ---------------------------------------------------------------------------

def test_demote_moves_future_dated_today_tasks_back_to_inbox(db_session):
    user = _user(db_session)
    today = _app_today(user)
    bad = _mk_task(db_session, user.id, status=TaskStatus.today,
                   due_date=today + timedelta(days=3))
    ok = _mk_task(db_session, user.id, status=TaskStatus.today, due_date=today)

    moved = demote_misclassified_today(user, db_session)
    assert moved == 1
    db_session.refresh(bad)
    db_session.refresh(ok)
    assert bad.status == TaskStatus.inbox
    assert ok.status == TaskStatus.today


def test_demote_ignores_routines(db_session):
    user = _user(db_session)
    today = _app_today(user)
    routine_task = _mk_task(
        db_session, user.id, status=TaskStatus.today,
        due_date=today + timedelta(days=3),
        task_type=TaskType.routine, routine_id=1,
    )
    demote_misclassified_today(user, db_session)
    db_session.refresh(routine_task)
    assert routine_task.status == TaskStatus.today


# ---------------------------------------------------------------------------
# promote_due_tasks: inbox w/ due_date <= today → today
# ---------------------------------------------------------------------------

def test_promote_moves_overdue_inbox_to_today(db_session):
    user = _user(db_session)
    today = _app_today(user)
    overdue = _mk_task(db_session, user.id, status=TaskStatus.inbox,
                       due_date=today - timedelta(days=1))
    future = _mk_task(db_session, user.id, status=TaskStatus.inbox,
                      due_date=today + timedelta(days=1))

    promote_due_tasks(user, db_session)
    db_session.refresh(overdue)
    db_session.refresh(future)
    assert overdue.status == TaskStatus.today
    assert future.status == TaskStatus.inbox


# ---------------------------------------------------------------------------
# archive_past_appointments: a missed appointment is over — auto-complete and
# archive it (same as any completed task) instead of letting it resurface.
# ---------------------------------------------------------------------------

def test_archive_past_appointments_completes_them(db_session):
    user = _user(db_session)
    today = _app_today(user)
    missed_today = _mk_task(db_session, user.id, status=TaskStatus.today,
                            task_type=TaskType.appointment,
                            due_date=today - timedelta(days=2))
    missed_inbox = _mk_task(db_session, user.id, status=TaskStatus.inbox,
                            task_type=TaskType.appointment,
                            due_date=today - timedelta(days=5))
    todays_appt = _mk_task(db_session, user.id, status=TaskStatus.today,
                           task_type=TaskType.appointment, due_date=today)

    n = archive_past_appointments(user, db_session)
    assert n == 2
    db_session.refresh(missed_today)
    db_session.refresh(missed_inbox)
    db_session.refresh(todays_appt)
    assert missed_today.status == TaskStatus.done
    assert missed_today.completed_at is not None
    assert missed_inbox.status == TaskStatus.done
    assert todays_appt.status == TaskStatus.today   # today's appointment untouched


def test_archive_past_appointments_ignores_plain_tasks(db_session):
    user = _user(db_session)
    today = _app_today(user)
    overdue_task = _mk_task(db_session, user.id, status=TaskStatus.inbox,
                            task_type=TaskType.task,
                            due_date=today - timedelta(days=3))
    archive_past_appointments(user, db_session)
    db_session.refresh(overdue_task)
    assert overdue_task.status == TaskStatus.inbox   # overdue tasks stay actionable
